# Generated by Django 3.2.8 on 2023-07-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotesMadera',
            fields=[
                ('idLote', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoMadera',
            fields=[
                ('idTipoMadera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('valorPie', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PiezaMadera',
            fields=[
                ('idPieza', models.AutoField(primary_key=True, serialize=False)),
                ('alto', models.PositiveSmallIntegerField(max_length=100)),
                ('ancho', models.PositiveSmallIntegerField(max_length=100)),
                ('largo', models.PositiveSmallIntegerField(max_length=200)),
                ('valorPie', models.PositiveIntegerField()),
                ('loteMadera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CalcularValor.lotesmadera')),
                ('tipoMadera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CalcularValor.tipomadera')),
            ],
        ),
    ]
