# Generated by Django 3.2.8 on 2023-07-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalcularValor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piezamadera',
            name='alto',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='piezamadera',
            name='ancho',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='piezamadera',
            name='largo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
