# Generated by Django 3.2.8 on 2023-07-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalcularValor', '0002_auto_20230709_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezamadera',
            name='loteMadera',
        ),
        migrations.RemoveField(
            model_name='piezamadera',
            name='valorPie',
        ),
        migrations.AlterField(
            model_name='piezamadera',
            name='alto',
            field=models.PositiveSmallIntegerField(verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='piezamadera',
            name='ancho',
            field=models.PositiveSmallIntegerField(verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='piezamadera',
            name='largo',
            field=models.PositiveSmallIntegerField(verbose_name='Largo'),
        ),
    ]
