# Generated by Django 3.2.8 on 2023-07-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalcularValor', '0003_auto_20230709_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezamadera',
            name='valorPieza',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
