# Generated by Django 3.2.8 on 2023-07-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalcularValor', '0004_piezamadera_valorpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezamadera',
            name='idLote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CalcularValor.lotesmadera'),
        ),
    ]
