# Generated by Django 3.2.8 on 2023-07-23 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalcularValor', '0006_alter_piezamadera_valorpieza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piezamadera',
            name='idLote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CalcularValor.lotesmadera'),
        ),
    ]
