# Generated by Django 3.2.8 on 2023-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalcularValor', '0007_alter_piezamadera_idlote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotesmadera',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
